
package com.nsc.dem.webservice.client.edm;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "EDMService", targetNamespace = "http://www.example.org/EDMService/", wsdlLocation = "http://192.168.3.9:7001/jyy/EDMServiceSOAP?wsdl")
public class EDMService_Service
    extends Service
{

    //private final static URL EDMSERVICE_WSDL_LOCATION;
    private final static QName SERVICE = new QName("http://www.example.org/EDMService/", "EDMService");
    
    static {
       // URL url = null;
        //EDMSERVICE_WSDL_LOCATION = url;
    }

    public EDMService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EDMService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    /**
     * 
     * @return
     *     returns EDMService
     */
    @WebEndpoint(name = "EDMServiceSOAP")
    public EDMService getEDMServiceSOAP() {
        return (EDMService)super.getPort(new QName("http://www.example.org/EDMService/", "EDMServiceSOAP"), EDMService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EDMService
     */
    @WebEndpoint(name = "EDMServiceSOAP")
    public EDMService getEDMServiceSOAP(WebServiceFeature... features) {
        return (EDMService)super.getPort(new QName("http://www.example.org/EDMService/", "EDMServiceSOAP"), EDMService.class, features);
    }

}
