package com.nsc.dem.webservice.server;

import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlMimeType;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "EDMService", targetNamespace = "http://www.example.org/EDMService/")
public interface EDMService {

	/**
	 * 
	 * @param stream
	 * @param in
	 * @return returns boolean
	 * @throws Exception
	 */
	@WebMethod(action = "http://www.example.org/EDMService/publishReviewPlanInfo")
	@WebResult(name = "out", targetNamespace = "")
	public boolean publishReviewPlanInfo(
			@WebParam(name = "stream", targetNamespace = "") String stream)
			throws Exception;

	@WebMethod(action = "http://www.example.org/EDMService/getUserInfo")
	@WebResult(name = "out", targetNamespace = "")
	public byte[] getUserInfo(
			@WebParam(name = "param", targetNamespace = "") String param,
			@WebParam(name = "pwd", targetNamespace = "") String pwd);


	
/*****************************以下接口为数据同步、跨域统计、就近取文档、分布式分检索服务******************************************************************/
	/**
	 * 跨域统计
	 * 
	 * @param param
	 */
	@WebMethod(action = "http://www.example.org/EDMService/crossdomainStatistics")
	@WebResult(name = "out", targetNamespace = "")
	public void crossdomainStatistics(
			@WebParam(name = "param", targetNamespace = "") String param,
			@WebParam(name = "pwd", targetNamespace = "") String pwd)
			throws Exception;

	

	/**
	 * 接收文件清单接口
	 * 
	 * @param input
	 * @return
	 */
	@WebMethod(action = "http://www.example.org/EDMService/receiveFileList")
	@WebResult(name = "out", targetNamespace = "")
	public boolean receiveFileList(
			@XmlMimeType("application/octet-stream") DataHandler dataHandler ,
			@WebParam(name = "pwd", targetNamespace = "") String pwd);

	/**
	 * 接收省公司发送的服务服务器信息
	 * @param unitCode 单位ID
	 * @param unitname 单位名称
	 * @param ftpIp  IP
	 * @param ftpLonginName 用户名
	 * @param ftpLoginPass  密码
	 * @param ftpPort  端口号
	 * @param wsAdd    webService地址
	 * @return
	 * @throws Exception
	 */
	@WebMethod(action = "http://www.example.org/EDMService/saveServersInfo")
	@WebResult(name = "out", targetNamespace = "")
	public boolean saveServersInfo(
			@WebParam(name = "unitCode", targetNamespace = "") String unitCode,
			@WebParam(name = "unitName", targetNamespace = "") String unitname,
			@WebParam(name = "ftpIp", targetNamespace = "") String ftpIp,
			@WebParam(name = "ftpLonginName", targetNamespace = "") String ftpLonginName,
			@WebParam(name = "ftpLoginPass", targetNamespace = "") String ftpLoginPass,
			@WebParam(name = "ftpPort", targetNamespace = "") String ftpPort,
			@WebParam(name = "wsAdd", targetNamespace = "") String wsAdd,
			@WebParam(name = "pwd", targetNamespace = "") String pwd)
			throws Exception;

	/**
	 * 查询服务器信息
	 * 
	 * @return list对象
	 */
	@WebMethod(action = "http://www.example.org/EDMService/findServersInfo")
	@WebResult(name = "out", targetNamespace = "")
	public String findServersInfo(
			@WebParam(name = "pwd", targetNamespace = "") String pwd
	) throws Exception;
	
	/**
	 * 接收国家电网发送的服务器信息
	 * @param ftpContent ftp.xml
	 * @param intenterContent intenter.xml
	 */
	@WebMethod(action = "http://www.example.org/EDMService/receiveAllServersInfo")
	@WebResult(name = "out", targetNamespace = "")
	public void receiveAllServersInfo(
			@WebParam(name = "ftpContent", targetNamespace = "") String ftpContent,
			@WebParam(name = "intenterContent", targetNamespace = "") String intenterContent,
			@WebParam(name = "pwd", targetNamespace = "") String pwd)
			throws Exception;

	/**
	 * 接收省公司发传送的部分部分服务器信息
	 * @param ftpContent  ftp节点
	 * @param intenterContent intenter节点
	 */
	@WebMethod(action = "http://www.example.org/EDMService/receivePartServersInfo")
	@WebResult(name = "out", targetNamespace = "")
	public void receivePartServersInfo(
			@WebParam(name = "ftpContent", targetNamespace = "") String ftpContent,
			@WebParam(name = "intenterContent", targetNamespace = "") String intenterContent,
			@WebParam(name = "pwd", targetNamespace = "") String pwd)
			throws Exception;
	
	
	
	
	/**
	 * 检查用户信息，并把用户需要下载的文件发送给调用者
	 *   国家电网下载文件时查询省公司的文件信息
	 * @param docId 文档ID
	 */
	@WebMethod(action = "http://www.example.org/EDMService/getFileInfo")
	@WebResult(name = "out", targetNamespace = "")
	public String getDownLoadFile(
			@WebParam(name = "username", targetNamespace = "") String username,
			@WebParam(name = "password", targetNamespace = "") String password,
			@WebParam(name = "fileName", targetNamespace = "") String fileName,
			@WebParam(name = "pwd", targetNamespace = "") String pwd
			)
			throws Exception;
	
	/**
	 * 执行任务
	 */
	@WebMethod(action = "http://www.example.org/EDMService/doExceuteTask")
	@WebResult(name = "out", targetNamespace = "")
	public String doExceuteTask(
			@WebParam(name = "methodname", targetNamespace = "") String methodname,
			@WebParam(name = "pwd", targetNamespace = "") String pwd)
			throws Exception;
	
	/**
	 * 接收同步成功和失败的文件ID
	 * @param successFileID 成功的文件ID
	 * @param failFileID    失败的文件ID
	 * @return
	 */
	@WebMethod(action = "http://www.example.org/EDMService/receiveSynFileID")
	@WebResult(name = "out", targetNamespace = "")
	public boolean receiveSynFileID(
			@WebParam(name = "successFileID", targetNamespace = "") String successFileID,
			@WebParam(name = "failFileID", targetNamespace = "") String failFileID,
			@WebParam(name = "unitCode", targetNamespace = "") String unitCode,
			@WebParam(name = "pwd", targetNamespace = "") String pwd
	);
	
}
